### ISSUE TITLE
Sahas-Colour_Sensor

### ISSUE THREAD

**Issue by Sahas00** [RoboManipal-9-0/First-year-Task-phase#2]
## DEADLINE: 
21.10.2018
## NAME : 
SAHAS AGARWAL
## TASK ASSIGNED TO: 
@Sahas00 
## TASK: 
COLOUR SENSING WITH ARDUINO USING TCS3200
## TASK LIST: 
- [x] Writing the code for the module
- [x] Created a README.md file for the module
- [x] Uploaded necessary files
- [x] Committed all changes
