### ISSUE TITLE
Yash_IR_Line_Follower

### ISSUE THREAD

**Issue by yashrampuria** [RoboManipal-9-0/First-year-Task-phase#3]
## DEADLINE: 
22.10.2018(12 am)
## TASK ASSIGNED TO: 
@yashrampuria 
## TASK: 
IR Line Follower Bot
## TASK LIST: 
- [x] Writing the code for the bot to move forward , left , right or stop.
- [x] Created a README.md file for the module
- [x] Write an issue
- [x] Committed all changes
